version: '3.4'

services:
  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "project.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/project'
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'


  database:
    image: postgres:14
    container_name: project_database
    restart: always
    env_file:
      - '.env'
    volumes:
        - ./data:/var/lib/postgresql/data
        - ./dbconf/postgres.conf:/etc/postgresql/postgresql.conf
        - ./dbconf/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - '5432:5432'